-- Migration: 004_reminder_subscriptions
-- Phase 2: Reminder subscriptions
--
-- Anonymous per-device subscription to event reminders.
-- Stored server-side (not on device).
-- Subscribe/unsubscribe per event.
--
-- Rules:
-- - One subscription per device per event
-- - Mobile NEVER generates reminders
-- - Reminders are generated by backend job at 00:01 Europe/Zagreb

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Reminder subscriptions table
CREATE TABLE IF NOT EXISTS reminder_subscriptions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Device ID (anonymous identifier)
  device_id TEXT NOT NULL,

  -- Event being subscribed to
  event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE,

  -- Timestamp
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Unique constraint: one subscription per device per event
  UNIQUE(device_id, event_id)
);

-- Index for querying subscriptions by event (for reminder generation)
CREATE INDEX IF NOT EXISTS idx_reminder_subscriptions_event_id
  ON reminder_subscriptions(event_id);

-- Index for querying subscriptions by device (for user's subscriptions list)
CREATE INDEX IF NOT EXISTS idx_reminder_subscriptions_device_id
  ON reminder_subscriptions(device_id);

-- Comment
COMMENT ON TABLE reminder_subscriptions IS 'Anonymous per-device reminder subscriptions (Phase 2)';
