/**
 * PageEditPage Styles
 *
 * Extracted from PageEditPage.tsx for maintainability.
 * Part of PageEditPage refactoring (Phase 1/4).
 */

import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  container: {
    padding: '24px',
    maxWidth: '1000px',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
  },
  headerActions: {
    display: 'flex',
    gap: '8px',
  },
  title: {
    fontSize: '24px',
    fontWeight: 'bold',
    margin: 0,
  },
  statusBar: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '12px 16px',
    backgroundColor: '#f8f9fa',
    borderRadius: '4px',
    marginBottom: '16px',
    fontSize: '14px',
  },
  statusDate: {
    color: '#666666',
  },
  error: {
    padding: '12px 16px',
    backgroundColor: '#f8d7da',
    color: '#721c24',
    borderRadius: '4px',
    marginBottom: '16px',
  },
  success: {
    padding: '12px 16px',
    backgroundColor: '#d4edda',
    color: '#155724',
    borderRadius: '4px',
    marginBottom: '16px',
  },
  loading: {
    padding: '48px',
    textAlign: 'center',
    color: '#666666',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  section: {
    backgroundColor: '#ffffff',
    padding: '20px',
    borderRadius: '8px',
    border: '1px solid #e0e0e0',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
  },
  sectionTitle: {
    fontSize: '16px',
    fontWeight: '600',
    margin: 0,
  },
  hint: {
    fontSize: '13px',
    color: '#666666',
    margin: '0 0 16px 0',
  },
  field: {
    flex: 1,
    marginBottom: '12px',
  },
  fieldRow: {
    display: 'flex',
    gap: '16px',
  },
  label: {
    display: 'block',
    fontSize: '14px',
    fontWeight: '500',
    marginBottom: '6px',
    color: '#333333',
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    fontSize: '14px',
    border: '1px solid #ddd',
    borderRadius: '4px',
    boxSizing: 'border-box',
  },
  select: {
    width: '200px',
    padding: '10px 12px',
    fontSize: '14px',
    border: '1px solid #ddd',
    borderRadius: '4px',
  },
  textarea: {
    width: '100%',
    padding: '10px 12px',
    fontSize: '14px',
    border: '1px solid #ddd',
    borderRadius: '4px',
    resize: 'vertical',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
  },
  actions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
  },
  cancelButton: {
    padding: '10px 20px',
    backgroundColor: '#ffffff',
    color: '#333333',
    border: '1px solid #ddd',
    borderRadius: '4px',
    fontSize: '14px',
    cursor: 'pointer',
  },
  saveButton: {
    padding: '12px 24px',
    backgroundColor: '#000000',
    color: '#ffffff',
    border: 'none',
    borderRadius: '4px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  publishButton: {
    padding: '10px 20px',
    backgroundColor: '#28a745',
    color: '#ffffff',
    border: 'none',
    borderRadius: '4px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  unpublishButton: {
    padding: '10px 20px',
    backgroundColor: '#dc3545',
    color: '#ffffff',
    border: 'none',
    borderRadius: '4px',
    fontSize: '14px',
    cursor: 'pointer',
  },
  emptyBlocks: {
    padding: '32px',
    textAlign: 'center',
    color: '#666666',
    backgroundColor: '#f8f9fa',
    borderRadius: '4px',
  },
  dropdown: {
    position: 'relative',
  },
  addBlockButton: {
    padding: '8px 16px',
    backgroundColor: '#ffffff',
    color: '#333333',
    border: '1px solid #ddd',
    borderRadius: '4px',
    fontSize: '13px',
    cursor: 'pointer',
  },
  dropdownMenu: {
    position: 'absolute',
    top: '100%',
    right: 0,
    marginTop: '4px',
    backgroundColor: '#ffffff',
    border: '1px solid #ddd',
    borderRadius: '4px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    zIndex: 10,
    minWidth: '160px',
  },
  dropdownItem: {
    display: 'block',
    width: '100%',
    padding: '10px 16px',
    textAlign: 'left',
    border: 'none',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    fontSize: '14px',
  },
  dropdownItemDisabled: {
    color: '#999999',
    cursor: 'not-allowed',
  },
  blockCard: {
    marginBottom: '16px',
    border: '1px solid #e0e0e0',
    borderRadius: '8px',
    overflow: 'hidden',
  },
  blockHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    backgroundColor: '#f8f9fa',
    borderBottom: '1px solid #e0e0e0',
  },
  blockIndex: {
    fontSize: '12px',
    color: '#666666',
    fontWeight: '600',
  },
  blockType: {
    fontSize: '14px',
    fontWeight: '500',
    flex: 1,
  },
  blockLocks: {
    display: 'flex',
    gap: '4px',
  },
  lockBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '20px',
    height: '20px',
    backgroundColor: '#ffc107',
    color: '#333333',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: 'bold',
  },
  lockToggles: {
    display: 'flex',
    gap: '12px',
    marginLeft: '8px',
  },
  lockToggle: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    cursor: 'pointer',
    fontSize: '12px',
    color: '#666666',
  },
  lockCheckbox: {
    width: '14px',
    height: '14px',
    cursor: 'pointer',
  },
  lockToggleLabel: {
    userSelect: 'none',
  },
  reorderButtons: {
    display: 'flex',
    gap: '4px',
  },
  reorderButton: {
    width: '28px',
    height: '28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    color: '#333333',
    border: '1px solid #ddd',
    borderRadius: '4px',
    fontSize: '14px',
    cursor: 'pointer',
  },
  removeBlockButton: {
    padding: '4px 8px',
    backgroundColor: '#ffffff',
    color: '#dc3545',
    border: '1px solid #dc3545',
    borderRadius: '4px',
    fontSize: '12px',
    cursor: 'pointer',
  },
  blockContent: {
    padding: '16px',
  },
  noticeInfo: {
    padding: '16px',
    backgroundColor: '#fff3cd',
    color: '#856404',
    fontSize: '14px',
  },
  lockedInfo: {
    padding: '16px',
    backgroundColor: '#f8f9fa',
    color: '#666666',
    fontSize: '14px',
  },
  notImplementedInfo: {
    padding: '16px',
    backgroundColor: '#f8f9fa',
    color: '#666666',
    fontSize: '14px',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  // LinkList editor styles
  emptyList: {
    padding: '24px',
    textAlign: 'center',
    color: '#999999',
    fontStyle: 'italic',
    backgroundColor: '#fafafa',
    borderRadius: '4px',
    marginBottom: '12px',
  },
  linkItem: {
    padding: '12px',
    marginBottom: '12px',
    border: '1px solid #e0e0e0',
    borderRadius: '6px',
    backgroundColor: '#fafafa',
  },
  linkItemHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  linkItemIndex: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#666666',
  },
  linkItemActions: {
    display: 'flex',
    gap: '4px',
  },
  linkReorderBtn: {
    width: '24px',
    height: '24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    color: '#333333',
    border: '1px solid #ddd',
    borderRadius: '4px',
    fontSize: '12px',
    cursor: 'pointer',
  },
  linkRemoveBtn: {
    width: '24px',
    height: '24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    color: '#dc3545',
    border: '1px solid #dc3545',
    borderRadius: '4px',
    fontSize: '12px',
    cursor: 'pointer',
  },
  addLinkButton: {
    padding: '10px 16px',
    backgroundColor: '#ffffff',
    color: '#333333',
    border: '1px dashed #ccc',
    borderRadius: '4px',
    fontSize: '14px',
    cursor: 'pointer',
    width: '100%',
  },
  fieldError: {
    color: '#dc3545',
    fontSize: '12px',
    fontWeight: 'normal',
  },
  inputError: {
    borderColor: '#dc3545',
  },
  // Contact editor styles
  contactItem: {
    padding: '16px',
    marginBottom: '16px',
    border: '1px solid #e0e0e0',
    borderRadius: '8px',
    backgroundColor: '#fafafa',
  },
  contactItemHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
    paddingBottom: '12px',
    borderBottom: '1px solid #e0e0e0',
  },
  contactItemIndex: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#333333',
  },
  contactItemActions: {
    display: 'flex',
    gap: '4px',
  },
  contactReorderBtn: {
    width: '28px',
    height: '28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    color: '#333333',
    border: '1px solid #ddd',
    borderRadius: '4px',
    fontSize: '14px',
    cursor: 'pointer',
  },
  contactRemoveBtn: {
    width: '28px',
    height: '28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    color: '#dc3545',
    border: '1px solid #dc3545',
    borderRadius: '4px',
    fontSize: '14px',
    cursor: 'pointer',
  },
  addContactButton: {
    padding: '12px 16px',
    backgroundColor: '#ffffff',
    color: '#333333',
    border: '1px dashed #ccc',
    borderRadius: '4px',
    fontSize: '14px',
    cursor: 'pointer',
    width: '100%',
  },
  phoneRow: {
    display: 'flex',
    gap: '8px',
    marginBottom: '8px',
  },
  phoneInput: {
    flex: 1,
    padding: '8px 12px',
    fontSize: '14px',
    border: '1px solid #ddd',
    borderRadius: '4px',
    boxSizing: 'border-box',
  },
  phoneRemoveBtn: {
    width: '32px',
    height: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    color: '#dc3545',
    border: '1px solid #dc3545',
    borderRadius: '4px',
    fontSize: '12px',
    cursor: 'pointer',
    flexShrink: 0,
  },
  addPhoneButton: {
    padding: '6px 12px',
    backgroundColor: '#ffffff',
    color: '#666666',
    border: '1px dashed #ccc',
    borderRadius: '4px',
    fontSize: '12px',
    cursor: 'pointer',
  },
  // CardList editor styles
  cardItem: {
    padding: '16px',
    marginBottom: '16px',
    border: '1px solid #e0e0e0',
    borderRadius: '8px',
    backgroundColor: '#fafafa',
  },
  cardItemHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
    paddingBottom: '12px',
    borderBottom: '1px solid #e0e0e0',
  },
  cardItemIndex: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#333333',
  },
  cardItemActions: {
    display: 'flex',
    gap: '4px',
  },
  cardReorderBtn: {
    width: '28px',
    height: '28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    color: '#333333',
    border: '1px solid #ddd',
    borderRadius: '4px',
    fontSize: '14px',
    cursor: 'pointer',
  },
  cardRemoveBtn: {
    width: '28px',
    height: '28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    color: '#dc3545',
    border: '1px solid #dc3545',
    borderRadius: '4px',
    fontSize: '14px',
    cursor: 'pointer',
  },
  addCardButton: {
    padding: '12px 16px',
    backgroundColor: '#ffffff',
    color: '#333333',
    border: '1px dashed #ccc',
    borderRadius: '4px',
    fontSize: '14px',
    cursor: 'pointer',
    width: '100%',
  },
  // Media editor styles
  mediaPreview: {
    marginBottom: '16px',
    padding: '12px',
    backgroundColor: '#f8f9fa',
    borderRadius: '6px',
    border: '1px solid #e0e0e0',
  },
  mediaPreviewImage: {
    maxWidth: '100%',
    maxHeight: '160px',
    display: 'block',
    borderRadius: '4px',
  },
  mediaPreviewLink: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  mediaPreviewLabel: {
    fontSize: '12px',
    color: '#666666',
    fontWeight: '500',
  },
  mediaPreviewUrl: {
    fontSize: '13px',
    color: '#333333',
    wordBreak: 'break-all',
  },
  // Map editor styles
  mapCoordinatesSection: {
    marginBottom: '16px',
    padding: '12px',
    backgroundColor: '#f8f9fa',
    borderRadius: '6px',
    border: '1px solid #e0e0e0',
  },
  mapLinkContainer: {
    marginTop: '12px',
    paddingTop: '12px',
    borderTop: '1px solid #e0e0e0',
  },
  mapLink: {
    color: '#0066cc',
    textDecoration: 'none',
    fontSize: '14px',
    fontWeight: '500',
  },
};
